version: '3.4'

networks:
  comment-book-network:
    driver: bridge

services:
  apicommentbook:
    image: ${DOCKER_REGISTRY-}apicommentbook
    depends_on:
        - "postgres"
    build:
      context: .
      dockerfile: APICommentBook/Dockerfile
    ports:
        - "8000:80"
   # environment:
    #DB_CONNECTION_STRING: "host="
    networks:
        - "comment-book-network"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=mydbname2
    volumes:
      - ./volumes/data/db:/var/lib/postgresql/data
      - ./dbscripts:/docker-entrypoint-initdb.d
    ports:
       - 5432:5432
    restart: always
    networks:
        - "comment-book-network"

